"""Smoke tests — fast, hermetic checks that catch obvious breakage.

These run on every push via .github/workflows/ci.yml. They must NOT
require a database connection, network, or any external service. Any
test that needs those belongs in a separate integration suite.
"""

import pytest


# ─── Bank statement parser ──────────────────────────────────────────


def test_bank_parser_reports_unsupported_format_clearly():
    """Caller passing a bogus content type gets a ValueError, not silent 0 results."""
    from app.services.bank_parser_service import BankStatementAIParser

    parser = BankStatementAIParser()
    with pytest.raises(ValueError):
        parser.parse_bank_statement(b"not a real file", "application/octet-stream", "x.bin")


def test_bank_parser_anthropic_imports_resolve():
    """Import-level smoke for the anthropic-error catches we added so we
    don't ship a NameError if the SDK shape changes."""
    import anthropic

    assert hasattr(anthropic, "AuthenticationError")
    assert hasattr(anthropic, "BadRequestError")
    assert hasattr(anthropic, "RateLimitError")


# ─── Bulk-upload template <-> parser round-trip ─────────────────────


def test_bulk_upload_template_round_trip_is_warning_free():
    """Fresh template generated by build_template_bytes() must parse cleanly
    via parse_bulk_upload — ensures column order stays in sync."""
    from app.services.bulk_upload_service import parse_bulk_upload
    from app.services.bulk_upload_template import build_template_bytes

    result = parse_bulk_upload(build_template_bytes())
    assert result["warnings"] == [], f"Template parsed with warnings: {result['warnings']}"
    summary = result["summary"]
    assert summary["total_apartments"] == 4, f"Expected 4 example apts, got {summary}"
    assert summary["budget_line_count"] == 6
    assert summary["has_financing"] is True


def test_bulk_upload_keeps_inventory_row_when_building_is_empty():
    """The parser-fix from this batch: rows where building is empty but
    other identifying columns have data must be kept."""
    import io
    import openpyxl

    from app.services.bulk_upload_service import parse_bulk_upload

    wb = openpyxl.Workbook()
    wb.remove(wb.active)
    ws = wb.create_sheet("מלאי מגורים יזם")
    ws.cell(row=1, column=1, value="building")  # header — parser skips row 1
    # Building empty, unit_number present → must be kept
    ws.append(["", "", "3", "12", "P3", "", "דירה", 4, 95.5, 0, 0, 1, 0, 0, 0, 0, 0, "לשיווק"])
    # Fully empty row → must be skipped
    ws.append([""] * 18)

    buf = io.BytesIO()
    wb.save(buf)
    result = parse_bulk_upload(buf.getvalue())

    apts = result["apartments_developer_residential"]
    assert len(apts) == 1, f"Expected 1 apt kept, got {len(apts)}"
    assert apts[0]["building_number"] == "A", "Empty building should default to 'A'"
    assert apts[0]["unit_number"] == "12"


# ─── Financing schema (new fields from the QA-list batch) ───────────


def test_financing_schema_accepts_guarantee_frameworks_and_investments():
    """Pydantic schema for the financing-setup PUT must accept the new
    structured guarantee list, pre-project investments, and the
    post-presale equity field."""
    from decimal import Decimal

    from app.schemas.setup import FinancingUpdate

    payload = FinancingUpdate(
        credit_limit_total=Decimal("35700000"),
        guarantee_frameworks=[
            {"label": "ערבות חוק מכר", "amount": "15000000", "kind": "sale_law"},
            {"label": "מסגרת קרקע", "amount": "13300000", "kind": "land_owner"},
        ],
        pre_project_investments=[
            {"label": "רכישת קרקע", "amount": "5000000", "approved_by": "משרד שמאים"},
        ],
        equity_required_after_presale=Decimal("3000000"),
    )
    dumped = payload.model_dump(mode="json")
    assert len(dumped["guarantee_frameworks"]) == 2
    assert dumped["pre_project_investments"][0]["approved_by"] == "משרד שמאים"
    assert dumped["equity_required_after_presale"] == "3000000"


def test_monthly_report_create_requires_index_and_vat():
    """Item C: index and VAT must be captured at report creation, not later."""
    import pydantic
    from app.schemas.monthly import MonthlyReportCreate

    # Both required → omitting either raises
    with pytest.raises(pydantic.ValidationError):
        MonthlyReportCreate(report_month="2026-04-01")
    with pytest.raises(pydantic.ValidationError):
        MonthlyReportCreate(report_month="2026-04-01", current_index="138.4")
    # With both → ok
    payload = MonthlyReportCreate(
        report_month="2026-04-01", current_index="138.4", vat_rate="0.18",
    )
    assert str(payload.vat_rate) == "0.18"


def test_sales_contract_accepts_vat_rate_snapshot():
    """Item C: SalesContract takes a vat_rate snapshot so retroactive rate
    changes don't distort no-VAT side of past sales."""
    from app.schemas.monthly import SalesContractCreate, SalesContractResponse

    create = SalesContractCreate(
        apartment_id=1, buyer_name="x", contract_date="2026-04-01",
        final_price_with_vat="1000", final_price_no_vat="847.46",
        vat_rate="0.18",
    )
    assert str(create.vat_rate) == "0.18"
    assert "vat_rate" in SalesContractResponse.model_fields


def test_apartment_response_exposes_direction():
    """Inventory display needs the direction (כיוון) field — captured at upload
    via bulk_upload_service but missing from the API response until now."""
    from app.schemas.setup import ApartmentResponse

    fields = ApartmentResponse.model_fields
    assert "direction" in fields, "ApartmentResponse must expose 'direction'"


def test_project_update_schema_accepts_contractor_base_index_date():
    """ProjectUpdate must accept the new contractor_base_index_date so the
    financing page can persist the contractor agreement base index date."""
    from datetime import date

    from app.schemas.project import ProjectUpdate

    payload = ProjectUpdate(
        base_index="120.5",
        base_index_date=date(2024, 1, 1),
        contractor_base_index="118.7",
        contractor_base_index_date=date(2023, 12, 1),
    )
    assert payload.contractor_base_index_date == date(2023, 12, 1)


# ─── App boot smoke ─────────────────────────────────────────────────


def test_fastapi_app_imports_and_has_health_route():
    """The FastAPI app must import without exploding and expose a /health
    route — Railway's healthcheck depends on it."""
    from app.main import app

    routes = {getattr(r, "path", None) for r in app.routes}
    assert "/health" in routes, f"/health route missing. Routes: {sorted(p for p in routes if p)}"


def test_bulk_upload_template_endpoint_is_registered():
    """The new GET /setup/bulk-upload/template endpoint must be on the app."""
    from app.main import app

    paths = {getattr(r, "path", None) for r in app.routes}
    assert any(p and p.endswith("/setup/bulk-upload/template") for p in paths), (
        f"Template download route not registered. Got: {sorted(p for p in paths if p)}"
    )
